### ISSUE TITLE
Declarative way to describe an application's config

### ISSUE THREAD

**Issue by alldroll** [short-d/kgs#58]
The only way to get know about the application's config variables is to look at [main.go](https://github.com/short-d/kgs/blob/master/main.go#L18).

```
> GRPC_API_PORT=test ENABLE_ENCRYPTION=test scripts/./dev

panic: strconv.ParseBool: parsing "test": invalid syntax

goroutine 1 [running]:
main.mustBool(...)
	/home/alldroll/work/kgs/main.go:88
main.main()
	/home/alldroll/work/kgs/main.go:27 +0xc25
exit status 2

```
**I see several problems here**

* The reported error forces a developer to look at the code line in order to understand what kind of application's config variable is invalid. 
* It is difficult to understand which variables are required, which are optional.

As a solution, we can try to use a `struct` and the corresponding struct [tags](https://golang.org/pkg/reflect/#StructTag)

**Comment by naturetime10** [comment]
This is now provided by the app framework: https://github.com/short-d/app/blob/master/fw/envconfig/envconfig.go. Need to upgrade kgs to use it.
